services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./casas-victoria:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - casas-victoria

  app:
    build:
      args:
        user: casasvic
        uid: 1000
      context: .
      dockerfile: ./casas-victoria/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./casas-victoria:/var/www/html
      - ./casas-victoria/php.ini:/usr/local/etc/php/conf.d/php.ini
      - D:/Development/Proyectos/casas_victoria_admin/storage/houses-photos:/var/www/html/storage/app/photos
    networks:
      - casas-victoria
    ports:
      - 5173:5173

networks:
  casas-victoria: