version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./casas-victoria:/var/www/html
      - ./casas-victoria/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - casas-victoria

  app:
    build:
      args:
        user: salvador
        uid: 1000
      context: .
      dockerfile: ./casas-victoria/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./casas-victoria:/var/www/html
      - ./casas-victoria/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./storage/houses-photos:/var/www/html/storage/app/photos
    networks:
      - casas-victoria
    ports:
      - 5173:5173
    user: "www-data"
  
  wordpress:
    image: wordpress:php8.1
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: host.docker.internal
      WORDPRESS_DB_USER: sistemas
      WORDPRESS_DB_PASSWORD: sistemas
      WORDPRESS_DB_NAME: casas_victoria
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html
      - ./wordpress/casas-garcia-theme:/var/www/html/wp-content/themes/casas-garcia-theme/
      - ./wordpress/casas-catalog-plugin:/var/www/html/wp-content/plugins/casas-catalog-plugin/
      - ./storage/houses-photos:/var/www/html/wp-content/houses-photos/
    user: "www-data"
    networks:
      - casas-victoria
    depends_on:
      - app

networks:
  casas-victoria:

volumes:
  wordpress:
    driver: local