services:

  wordpress:
    image: wordpress:php8.1
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: host.docker.internal
      WORDPRESS_DB_USER: sistemas
      WORDPRESS_DB_PASSWORD: sistemas
      WORDPRESS_DB_NAME: casas_victoria
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html
      - ./casas-garcia-theme:/var/www/html/wp-content/themes/casas-garcia-theme/
      - ./casas-catalog-plugin:/var/www/html/wp-content/plugins/casas-catalog-plugin/
      - ./local_storage/houses-photos:/var/www/html/wp-content/houses-photos/

volumes:
  wordpress:
    driver: local